### ISSUE TITLE
DecryptingDeserializer does not support JsonDeserializer (ExtendedDeserializer)

### ISSUE THREAD

**Issue by marcus-j** [idealo/deckard#1]
The DecryptingDeserializer does not support JsonDeserializer as embedded deserializer. This is most likely caused by the JsonDeserializer being an implementation of ExtendedDeserializer<T> rather than directly Deserializer<T>.

```java
    @Test
    public void shouldDecryptOnJsonDeserialize() {
        EncryptingSerializer<MyPayload> encryptingSerializer = new EncryptingSerializer<>(PASS, SALT, new JsonSerializer<>());
        DecryptingDeserializer<MyPayload> decryptingDeserializer = new DecryptingDeserializer<>(PASS, SALT, new JsonDeserializer<>());
        byte[] encryptedData = encryptingSerializer.serialize("my-topic", new MyPayload("my-data"));
        MyPayload decryptedData = decryptingDeserializer.deserialize("my-topic", encryptedData);
        Assertions.assertThat(decryptedData).isEqualTo(new MyPayload("my-data"));
    }
```

causes _java.lang.IllegalArgumentException: Unrecognized Type: [null]_

**Comment by roechi** [comment]
First of all, to fix the issue at hand, you can initialize the JsonSerializer with a target type:
```java
JsonDeserializer<MyPayload> deserializer = new JsonDeserializer<>(MyPayload.class);
DecryptingDeserializer<MyPayload> decryptingDeserializer = new DecryptingDeserializer<>(PASS, SALT, deserializer);
```
Additionally, when not using shared DTOs, sending a `TypeId` header will most likely be problematic. In this case, you can make the deserializer ignore any type headers by using the disabling the flag `useHeadersIfPresent`:
```java
JsonDeserializer<MyPayload> deserializer = new JsonDeserializer<>(MyPayload.class, false);
DecryptingDeserializer<MyPayload> decryptingDeserializer = new DecryptingDeserializer<>(PASS, SALT, deserializer);
```
Nevertheless, I think it would be a good idea to also add a comfortable way to disable type header sending. The consumer should have control over how they want to name their DTOs. I will add this to the wanted features list.

**Comment by marcus-j** [comment]
Thanks @roechi ! You made my day :)

We should probably think about making type header suppression the default behaviour but still allow turning them back on.
