### ISSUE TITLE
Add support for kafka properties per producer

### ISSUE THREAD

**Issue by wanisfahmyDE** [idealo/deckard#4]
Currently kafka properties are applied to all producers even if they have different bootstrap servers leading the application to fail in startup.

Just as an example if one cluster has SSL configured and another not, the application will try to connect with all producers for all the bootstrap servers with this config, leading to SSL handshake exceptions.

**Comment by roechi** [comment]
I like this idea! However it proposes a pretty large feature. I will go ahead and let it marinate in my brain juices for a moment. Will come back to this!

**Comment by marcus-j** [comment]
I guess, we have several options:

1. We could simply add an optional producerFactory property to the KafkaProducer annotation, thus enabling any configuration one might want. However, this would make the whole approach of simplifying the configuration to a certain amount obsolete.

2. We could add optional properties to the KafkaProducer annotation for the most relevant cases, e.g. SSL configuration. However, this might get out of hand which each new requirement.

3. We could add an optional kafkaPropertyPrefix property to the KafkaProducer annotation. Any properties that are found with this prefix would override the global Spring Kafka properties.

What do you think?

**Comment by roechi** [comment]
I think the third option would be the most accessible/simple for users of Deckard. Also, it would introduce a quite organized and clean way of configuring many things. Basically, we could allow listing several fully fledged Kafka Properties under individual prefixes, also processing shouldn't be that hard if we do it like this. I like it.

**Comment by marcus-j** [comment]
@roechi, let's do it then :)
